### ISSUE TITLE
V 4.1.3 does not open dropdown

### ISSUE THREAD

**Issue by webdesignweisshart** [paypal/skipto#113]
After updating from 4.1.2 to 4.1.3, I can no longer open the dropdown menu. 
In the console I get the following error message:

Uncaught TypeError: Cannot set properties of undefined (setting 'innerHTML')
    at Object.renderMenuitemsToGroup (skipto.min.js:7:19287)
    at Object.renderMenu (skipto.min.js:7:24639)
    at Object.openPopup (skipto.min.js:7:27115)
    at Object.handleButtonKeydown (skipto.min.js:7:27716)
renderMenuitemsToGroup @ skipto.min.js:7
renderMenu @ skipto.min.js:7
openPopup @ skipto.min.js:7
handleButtonKeydown @ skipto.min.js:7

**Comment by jongund** [comment]
@webdesignweisshart 
Thank you for reporting this issue.
Can you send a the URL to the website you are having the problem?

**Comment by webdesignweisshart** [comment]
@jongund 
Thank you for your answer.

I found the reason.
In 4.1.2 I could use
landmarkGroupLabel:	" ",
in order to hide the landmarkGroupLabel.
In 4.1.3 I either have to remove this setting, or use any non-empty string.
My question now: Is it possible to hide the  landmarkGroupLabel in 4.1.3?

**Comment by jongund** [comment]
@webdesignweisshart 
I am curious why you don't want to show landmarks?
You have kind of identified an undocumented feature, that was not an indention in the original design.
In the original design it was hoped to help promote the proper use of landmarks.
So I would like to learn more from your perspective the importance of a feature to disable landmarks in the menu.

**Comment by CarlyGerard** [comment]
@jongund I'm noticing a similar issue today, but we're pointing to https://paypal.github.io/skipto/downloads/js/skipto.min.js which is now at 4.1.5. We use it on [https://www.wwu.edu](wwu.edu) if you want a live site to look to. We're getting the following error (Firefox):

```
Uncaught TypeError: this.lastMenuitem is undefined
    updateMenuitems https://paypal.github.io/skipto/downloads/js/skipto.min.js:7
    renderMenu https://paypal.github.io/skipto/downloads/js/skipto.min.js:7
    openPopup https://paypal.github.io/skipto/downloads/js/skipto.min.js:7
    handleButtonClick https://paypal.github.io/skipto/downloads/js/skipto.min.js:7
[skipto.min.js:7:16069](https://paypal.github.io/skipto/downloads/js/skipto.min.js)
    updateMenuitems https://paypal.github.io/skipto/downloads/js/skipto.min.js:7
    renderMenu https://paypal.github.io/skipto/downloads/js/skipto.min.js:7
    openPopup https://paypal.github.io/skipto/downloads/js/skipto.min.js:7
    handleButtonClick https://paypal.github.io/skipto/downloads/js/skipto.min.js:7
    handleButtonClick self-hosted:1178
```

**Comment by webdesignweisshart** [comment]
@jongund 
No, I don't want to hide the Landmarks, but only the label (heading) "Landmarks". My problem is that I can't find what I condider a generally understandable German translation for "landmarks", thus possibliy confusing visitors who don't know this term. I tried it with "Regionen" anyway, because I couldn't hide "landmarkGroupLabel" even with CSS.
[https://webdesign.weisshart.de/](url)

**Comment by webdesignweisshart** [comment]
@jongund @CarlyGerard 
Same here with 4.1.5. Menu doesn't drop down
Error msg:

> skipto_4.1.5.min.js:7 Uncaught TypeError: Cannot read properties of undefined (reading 'classList')
    at Object.updateMenuitems (skipto_4.1.5.min.js:7:16087)
    at Object.renderMenu (skipto_4.1.5.min.js:7:25736)
    at Object.openPopup (skipto_4.1.5.min.js:7:27138)
    at Object.handleButtonKeydown (skipto_4.1.5.min.js:7:27739)
updateMenuitems @ skipto_4.1.5.min.js:7
renderMenu @ skipto_4.1.5.min.js:7
openPopup @ skipto_4.1.5.min.js:7
handleButtonKeydown @ skipto_4.1.5.min.js:7

My settings:

 			"skipTo": {
				displayOption:		"popup",
				positionLeft:		"0",
				landmarkGroupLabel:	"Regionen",
				buttonLabel:		"Springe zu …",
				landmarks:			"[role=\'search\'],[role=\'main\'],[role=\'navigation\'],[role=\'contentinfo\']",
				headings:			"h1,h2,h3",
				accesskey:			"0",
				headingGroupLabel:	"Überschriften",
				mainLabel:			"Inhalt",
				searchLabel:		"Suche",
				footerLabel:		"Fußzeile",
				enableActions:		false,
				mofnGroupLabel:		" "
			}

**Comment by brianteeman** [comment]
I just checked to see what the german language translation team for Joomla used for landmarks and I see that they did not translate this term.

Further checks on google confirm that in german it is typically untranslated

**Comment by brianteeman** [comment]
@jongund from what I can tell it is the change you made in #114 that is causing this issue. I dont want to do a simple revert of that change as I'm not sure what it is you were trying to do with it

**Comment by jongund** [comment]
@brianteeman 
The problem was there before #114, the real issues is if someone through configuration makes an empty label, what should skipto do.  I think that it should just use the default value (.e.g. ignore empty configuration strings).

**Comment by jongund** [comment]
@webdesignweisshart 
You might check to see what a screen reader announces (e.g. JAWS, Voice Over, NVDA) for regions when using the German language.

**Comment by brianteeman** [comment]
@jongund all the examples fail right now - I dont see any empty labels

**Comment by brianteeman** [comment]
will do

**Comment by jongund** [comment]
@brianteeman 
Thanks, I think the problem is removing the `throw error` on line 359.  Unsupported configuration values should fail silently (e.g. default value is used) so the menu will still appear.

**Comment by brianteeman** [comment]
I've reverted those changes and made a new release 4.1.6. The examples and https://paypal.github.io/skipto/ work again.

@CarlyGerard sorry for the inconvenience and thanks for reporting the issue. 

@jongund no rush

**Comment by CarlyGerard** [comment]
Thanks @brianteeman @jongund for the quick fixing! Can confirm it's working again on our test page.
